modLoader="javafml"
loaderVersion="[36,)"
license = "MIT"
[[mods]]
modId="scenic"
version="${file.jarVersion}"
displayName="Scenic"
#updateJSONURL="http://myurl.me/"
displayURL="http://evilcult.net/scenicmod/"
logoFile="scenic.png"
itemIcon="scenic:treasure_pot"
authors="Vaelzan, Brunin, OrangeBurrito"
description='''
Scenic Mod

This mod adds a collection of new blocks and world generation targeted at terraformers and landscapers. We hope you
enjoy it!

'''

[[dependencies.scenic]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.scenic]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.16.5)"
    ordering="NONE"
    side="BOTH"
